### ISSUE TITLE
Secure boot

### ISSUE THREAD

**Issue by wudiqiang2024** [compulab-yokneam/Documentation#3]
@vraevsky  Hello, I am a user of compulab iotdin-imx8p, and we have a requirement to enable secure boot. I downloaded `linux-compulab` and `u-boot-compulab` from git, and used `cst-tools` to generate signature files of` Image, flash,bin, fuse.out`, but I don't know how to use these files to flash them into compulab later?
I am a novice in this area, can you provide me with some ideas and help?

**Comment by vraevsky** [comment]
@wudiqiang2024 
Please open up an issue at:
https://compulab.co.il/workspace/supportdb/index.php
